class OrderError(Exception): pass

class OrderCancelError(OrderError): pass